---
- name: check ssh connection
  wait_for_connection:
       delay: 5
       timeout: 20
  register: concheck
  ignore_errors: true


- fail:
    msg: Connection is failed < "{{ concheck.msg }}"
  when: concheck is failed

- debug:
    msg: Connection is successful.
  when: concheck is success
